// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbComment.proto

package com.xiaomi.zhibo.crawler.pb;

public final class PbComment {
  private PbComment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xiaomi.zhibo.crawler.pb.Comment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 from_uid = 1;</code>
     *
     * <pre>
     *发起评论人的ID
     * </pre>
     */
    boolean hasFromUid();
    /**
     * <code>required uint64 from_uid = 1;</code>
     *
     * <pre>
     *发起评论人的ID
     * </pre>
     */
    long getFromUid();

    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *评论内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *评论内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *评论内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>required uint64 create_time = 3;</code>
     *
     * <pre>
     * 创建时间
     * </pre>
     */
    boolean hasCreateTime();
    /**
     * <code>required uint64 create_time = 3;</code>
     *
     * <pre>
     * 创建时间
     * </pre>
     */
    long getCreateTime();

    /**
     * <code>optional uint64 to_uid = 4;</code>
     *
     * <pre>
     *被评论人ID
     * </pre>
     */
    boolean hasToUid();
    /**
     * <code>optional uint64 to_uid = 4;</code>
     *
     * <pre>
     *被评论人ID
     * </pre>
     */
    long getToUid();

    /**
     * <code>optional string from_nickname = 5;</code>
     *
     * <pre>
     *发起评论人的昵称
     * </pre>
     */
    boolean hasFromNickname();
    /**
     * <code>optional string from_nickname = 5;</code>
     *
     * <pre>
     *发起评论人的昵称
     * </pre>
     */
    java.lang.String getFromNickname();
    /**
     * <code>optional string from_nickname = 5;</code>
     *
     * <pre>
     *发起评论人的昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getFromNicknameBytes();

    /**
     * <code>optional string to_nickname = 6;</code>
     *
     * <pre>
     *被评论人昵称
     * </pre>
     */
    boolean hasToNickname();
    /**
     * <code>optional string to_nickname = 6;</code>
     *
     * <pre>
     *被评论人昵称
     * </pre>
     */
    java.lang.String getToNickname();
    /**
     * <code>optional string to_nickname = 6;</code>
     *
     * <pre>
     *被评论人昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getToNicknameBytes();

    /**
     * <code>optional bool is_good = 7;</code>
     *
     * <pre>
     *是否优质评论
     * </pre>
     */
    boolean hasIsGood();
    /**
     * <code>optional bool is_good = 7;</code>
     *
     * <pre>
     *是否优质评论
     * </pre>
     */
    boolean getIsGood();
  }
  /**
   * Protobuf type {@code com.xiaomi.zhibo.crawler.pb.Comment}
   */
  public static final class Comment extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.xiaomi.zhibo.crawler.pb.Comment)
      CommentOrBuilder {
    // Use Comment.newBuilder() to construct.
    private Comment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Comment(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Comment defaultInstance;
    public static Comment getDefaultInstance() {
      return defaultInstance;
    }

    public Comment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Comment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fromUid_ = input.readUInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              content_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              createTime_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              toUid_ = input.readUInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              fromNickname_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              toNickname_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              isGood_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_Comment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_Comment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiaomi.zhibo.crawler.pb.PbComment.Comment.class, com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder.class);
    }

    public static com.google.protobuf.Parser<Comment> PARSER =
        new com.google.protobuf.AbstractParser<Comment>() {
      public Comment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Comment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Comment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FROM_UID_FIELD_NUMBER = 1;
    private long fromUid_;
    /**
     * <code>required uint64 from_uid = 1;</code>
     *
     * <pre>
     *发起评论人的ID
     * </pre>
     */
    public boolean hasFromUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 from_uid = 1;</code>
     *
     * <pre>
     *发起评论人的ID
     * </pre>
     */
    public long getFromUid() {
      return fromUid_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.Object content_;
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *评论内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *评论内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 2;</code>
     *
     * <pre>
     *评论内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 3;
    private long createTime_;
    /**
     * <code>required uint64 create_time = 3;</code>
     *
     * <pre>
     * 创建时间
     * </pre>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 create_time = 3;</code>
     *
     * <pre>
     * 创建时间
     * </pre>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int TO_UID_FIELD_NUMBER = 4;
    private long toUid_;
    /**
     * <code>optional uint64 to_uid = 4;</code>
     *
     * <pre>
     *被评论人ID
     * </pre>
     */
    public boolean hasToUid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 to_uid = 4;</code>
     *
     * <pre>
     *被评论人ID
     * </pre>
     */
    public long getToUid() {
      return toUid_;
    }

    public static final int FROM_NICKNAME_FIELD_NUMBER = 5;
    private java.lang.Object fromNickname_;
    /**
     * <code>optional string from_nickname = 5;</code>
     *
     * <pre>
     *发起评论人的昵称
     * </pre>
     */
    public boolean hasFromNickname() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string from_nickname = 5;</code>
     *
     * <pre>
     *发起评论人的昵称
     * </pre>
     */
    public java.lang.String getFromNickname() {
      java.lang.Object ref = fromNickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromNickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string from_nickname = 5;</code>
     *
     * <pre>
     *发起评论人的昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFromNicknameBytes() {
      java.lang.Object ref = fromNickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromNickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_NICKNAME_FIELD_NUMBER = 6;
    private java.lang.Object toNickname_;
    /**
     * <code>optional string to_nickname = 6;</code>
     *
     * <pre>
     *被评论人昵称
     * </pre>
     */
    public boolean hasToNickname() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string to_nickname = 6;</code>
     *
     * <pre>
     *被评论人昵称
     * </pre>
     */
    public java.lang.String getToNickname() {
      java.lang.Object ref = toNickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toNickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string to_nickname = 6;</code>
     *
     * <pre>
     *被评论人昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getToNicknameBytes() {
      java.lang.Object ref = toNickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toNickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_GOOD_FIELD_NUMBER = 7;
    private boolean isGood_;
    /**
     * <code>optional bool is_good = 7;</code>
     *
     * <pre>
     *是否优质评论
     * </pre>
     */
    public boolean hasIsGood() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool is_good = 7;</code>
     *
     * <pre>
     *是否优质评论
     * </pre>
     */
    public boolean getIsGood() {
      return isGood_;
    }

    private void initFields() {
      fromUid_ = 0L;
      content_ = "";
      createTime_ = 0L;
      toUid_ = 0L;
      fromNickname_ = "";
      toNickname_ = "";
      isGood_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFromUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, fromUid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContentBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, createTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, toUid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getFromNicknameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getToNicknameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, isGood_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, fromUid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContentBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, createTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, toUid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFromNicknameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getToNicknameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isGood_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.Comment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xiaomi.zhibo.crawler.pb.PbComment.Comment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xiaomi.zhibo.crawler.pb.Comment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xiaomi.zhibo.crawler.pb.Comment)
        com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_Comment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_Comment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiaomi.zhibo.crawler.pb.PbComment.Comment.class, com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder.class);
      }

      // Construct using com.xiaomi.zhibo.crawler.pb.PbComment.Comment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromUid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        toUid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        fromNickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        toNickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        isGood_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_Comment_descriptor;
      }

      public com.xiaomi.zhibo.crawler.pb.PbComment.Comment getDefaultInstanceForType() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.Comment.getDefaultInstance();
      }

      public com.xiaomi.zhibo.crawler.pb.PbComment.Comment build() {
        com.xiaomi.zhibo.crawler.pb.PbComment.Comment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xiaomi.zhibo.crawler.pb.PbComment.Comment buildPartial() {
        com.xiaomi.zhibo.crawler.pb.PbComment.Comment result = new com.xiaomi.zhibo.crawler.pb.PbComment.Comment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromUid_ = fromUid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toUid_ = toUid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fromNickname_ = fromNickname_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.toNickname_ = toNickname_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.isGood_ = isGood_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiaomi.zhibo.crawler.pb.PbComment.Comment) {
          return mergeFrom((com.xiaomi.zhibo.crawler.pb.PbComment.Comment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiaomi.zhibo.crawler.pb.PbComment.Comment other) {
        if (other == com.xiaomi.zhibo.crawler.pb.PbComment.Comment.getDefaultInstance()) return this;
        if (other.hasFromUid()) {
          setFromUid(other.getFromUid());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasToUid()) {
          setToUid(other.getToUid());
        }
        if (other.hasFromNickname()) {
          bitField0_ |= 0x00000010;
          fromNickname_ = other.fromNickname_;
          onChanged();
        }
        if (other.hasToNickname()) {
          bitField0_ |= 0x00000020;
          toNickname_ = other.toNickname_;
          onChanged();
        }
        if (other.hasIsGood()) {
          setIsGood(other.getIsGood());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromUid()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!hasCreateTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiaomi.zhibo.crawler.pb.PbComment.Comment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiaomi.zhibo.crawler.pb.PbComment.Comment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long fromUid_ ;
      /**
       * <code>required uint64 from_uid = 1;</code>
       *
       * <pre>
       *发起评论人的ID
       * </pre>
       */
      public boolean hasFromUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 from_uid = 1;</code>
       *
       * <pre>
       *发起评论人的ID
       * </pre>
       */
      public long getFromUid() {
        return fromUid_;
      }
      /**
       * <code>required uint64 from_uid = 1;</code>
       *
       * <pre>
       *发起评论人的ID
       * </pre>
       */
      public Builder setFromUid(long value) {
        bitField0_ |= 0x00000001;
        fromUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 from_uid = 1;</code>
       *
       * <pre>
       *发起评论人的ID
       * </pre>
       */
      public Builder clearFromUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *评论内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *评论内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *评论内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *评论内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *评论内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 2;</code>
       *
       * <pre>
       *评论内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>required uint64 create_time = 3;</code>
       *
       * <pre>
       * 创建时间
       * </pre>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 create_time = 3;</code>
       *
       * <pre>
       * 创建时间
       * </pre>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>required uint64 create_time = 3;</code>
       *
       * <pre>
       * 创建时间
       * </pre>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000004;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 create_time = 3;</code>
       *
       * <pre>
       * 创建时间
       * </pre>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private long toUid_ ;
      /**
       * <code>optional uint64 to_uid = 4;</code>
       *
       * <pre>
       *被评论人ID
       * </pre>
       */
      public boolean hasToUid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 to_uid = 4;</code>
       *
       * <pre>
       *被评论人ID
       * </pre>
       */
      public long getToUid() {
        return toUid_;
      }
      /**
       * <code>optional uint64 to_uid = 4;</code>
       *
       * <pre>
       *被评论人ID
       * </pre>
       */
      public Builder setToUid(long value) {
        bitField0_ |= 0x00000008;
        toUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 to_uid = 4;</code>
       *
       * <pre>
       *被评论人ID
       * </pre>
       */
      public Builder clearToUid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toUid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object fromNickname_ = "";
      /**
       * <code>optional string from_nickname = 5;</code>
       *
       * <pre>
       *发起评论人的昵称
       * </pre>
       */
      public boolean hasFromNickname() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string from_nickname = 5;</code>
       *
       * <pre>
       *发起评论人的昵称
       * </pre>
       */
      public java.lang.String getFromNickname() {
        java.lang.Object ref = fromNickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromNickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string from_nickname = 5;</code>
       *
       * <pre>
       *发起评论人的昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFromNicknameBytes() {
        java.lang.Object ref = fromNickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromNickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string from_nickname = 5;</code>
       *
       * <pre>
       *发起评论人的昵称
       * </pre>
       */
      public Builder setFromNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fromNickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string from_nickname = 5;</code>
       *
       * <pre>
       *发起评论人的昵称
       * </pre>
       */
      public Builder clearFromNickname() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fromNickname_ = getDefaultInstance().getFromNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string from_nickname = 5;</code>
       *
       * <pre>
       *发起评论人的昵称
       * </pre>
       */
      public Builder setFromNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fromNickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toNickname_ = "";
      /**
       * <code>optional string to_nickname = 6;</code>
       *
       * <pre>
       *被评论人昵称
       * </pre>
       */
      public boolean hasToNickname() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string to_nickname = 6;</code>
       *
       * <pre>
       *被评论人昵称
       * </pre>
       */
      public java.lang.String getToNickname() {
        java.lang.Object ref = toNickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            toNickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string to_nickname = 6;</code>
       *
       * <pre>
       *被评论人昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getToNicknameBytes() {
        java.lang.Object ref = toNickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toNickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string to_nickname = 6;</code>
       *
       * <pre>
       *被评论人昵称
       * </pre>
       */
      public Builder setToNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        toNickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string to_nickname = 6;</code>
       *
       * <pre>
       *被评论人昵称
       * </pre>
       */
      public Builder clearToNickname() {
        bitField0_ = (bitField0_ & ~0x00000020);
        toNickname_ = getDefaultInstance().getToNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string to_nickname = 6;</code>
       *
       * <pre>
       *被评论人昵称
       * </pre>
       */
      public Builder setToNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        toNickname_ = value;
        onChanged();
        return this;
      }

      private boolean isGood_ ;
      /**
       * <code>optional bool is_good = 7;</code>
       *
       * <pre>
       *是否优质评论
       * </pre>
       */
      public boolean hasIsGood() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool is_good = 7;</code>
       *
       * <pre>
       *是否优质评论
       * </pre>
       */
      public boolean getIsGood() {
        return isGood_;
      }
      /**
       * <code>optional bool is_good = 7;</code>
       *
       * <pre>
       *是否优质评论
       * </pre>
       */
      public Builder setIsGood(boolean value) {
        bitField0_ |= 0x00000040;
        isGood_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_good = 7;</code>
       *
       * <pre>
       *是否优质评论
       * </pre>
       */
      public Builder clearIsGood() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isGood_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.xiaomi.zhibo.crawler.pb.Comment)
    }

    static {
      defaultInstance = new Comment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.xiaomi.zhibo.crawler.pb.Comment)
  }

  public interface MultiCreateFeedCommentsReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string feed_id = 1;</code>
     */
    boolean hasFeedId();
    /**
     * <code>required string feed_id = 1;</code>
     */
    java.lang.String getFeedId();
    /**
     * <code>required string feed_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getFeedIdBytes();

    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    java.util.List<com.xiaomi.zhibo.crawler.pb.PbComment.Comment> 
        getCommentsList();
    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    com.xiaomi.zhibo.crawler.pb.PbComment.Comment getComments(int index);
    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    int getCommentsCount();
    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    java.util.List<? extends com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder> 
        getCommentsOrBuilderList();
    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder getCommentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsReq}
   *
   * <pre>
   *cmd 1003: 批量增加评论
   * </pre>
   */
  public static final class MultiCreateFeedCommentsReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsReq)
      MultiCreateFeedCommentsReqOrBuilder {
    // Use MultiCreateFeedCommentsReq.newBuilder() to construct.
    private MultiCreateFeedCommentsReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MultiCreateFeedCommentsReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MultiCreateFeedCommentsReq defaultInstance;
    public static MultiCreateFeedCommentsReq getDefaultInstance() {
      return defaultInstance;
    }

    public MultiCreateFeedCommentsReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MultiCreateFeedCommentsReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              feedId_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                comments_ = new java.util.ArrayList<com.xiaomi.zhibo.crawler.pb.PbComment.Comment>();
                mutable_bitField0_ |= 0x00000002;
              }
              comments_.add(input.readMessage(com.xiaomi.zhibo.crawler.pb.PbComment.Comment.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          comments_ = java.util.Collections.unmodifiableList(comments_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq.class, com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq.Builder.class);
    }

    public static com.google.protobuf.Parser<MultiCreateFeedCommentsReq> PARSER =
        new com.google.protobuf.AbstractParser<MultiCreateFeedCommentsReq>() {
      public MultiCreateFeedCommentsReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiCreateFeedCommentsReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MultiCreateFeedCommentsReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FEED_ID_FIELD_NUMBER = 1;
    private java.lang.Object feedId_;
    /**
     * <code>required string feed_id = 1;</code>
     */
    public boolean hasFeedId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string feed_id = 1;</code>
     */
    public java.lang.String getFeedId() {
      java.lang.Object ref = feedId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          feedId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string feed_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFeedIdBytes() {
      java.lang.Object ref = feedId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feedId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENTS_FIELD_NUMBER = 2;
    private java.util.List<com.xiaomi.zhibo.crawler.pb.PbComment.Comment> comments_;
    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    public java.util.List<com.xiaomi.zhibo.crawler.pb.PbComment.Comment> getCommentsList() {
      return comments_;
    }
    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    public java.util.List<? extends com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder> 
        getCommentsOrBuilderList() {
      return comments_;
    }
    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    public int getCommentsCount() {
      return comments_.size();
    }
    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    public com.xiaomi.zhibo.crawler.pb.PbComment.Comment getComments(int index) {
      return comments_.get(index);
    }
    /**
     * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
     */
    public com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder getCommentsOrBuilder(
        int index) {
      return comments_.get(index);
    }

    private void initFields() {
      feedId_ = "";
      comments_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFeedId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCommentsCount(); i++) {
        if (!getComments(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFeedIdBytes());
      }
      for (int i = 0; i < comments_.size(); i++) {
        output.writeMessage(2, comments_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFeedIdBytes());
      }
      for (int i = 0; i < comments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, comments_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsReq}
     *
     * <pre>
     *cmd 1003: 批量增加评论
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsReq)
        com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq.class, com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq.Builder.class);
      }

      // Construct using com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCommentsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        feedId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (commentsBuilder_ == null) {
          comments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          commentsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_descriptor;
      }

      public com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq getDefaultInstanceForType() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq.getDefaultInstance();
      }

      public com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq build() {
        com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq buildPartial() {
        com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq result = new com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.feedId_ = feedId_;
        if (commentsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            comments_ = java.util.Collections.unmodifiableList(comments_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.comments_ = comments_;
        } else {
          result.comments_ = commentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq) {
          return mergeFrom((com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq other) {
        if (other == com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq.getDefaultInstance()) return this;
        if (other.hasFeedId()) {
          bitField0_ |= 0x00000001;
          feedId_ = other.feedId_;
          onChanged();
        }
        if (commentsBuilder_ == null) {
          if (!other.comments_.isEmpty()) {
            if (comments_.isEmpty()) {
              comments_ = other.comments_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCommentsIsMutable();
              comments_.addAll(other.comments_);
            }
            onChanged();
          }
        } else {
          if (!other.comments_.isEmpty()) {
            if (commentsBuilder_.isEmpty()) {
              commentsBuilder_.dispose();
              commentsBuilder_ = null;
              comments_ = other.comments_;
              bitField0_ = (bitField0_ & ~0x00000002);
              commentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCommentsFieldBuilder() : null;
            } else {
              commentsBuilder_.addAllMessages(other.comments_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFeedId()) {
          
          return false;
        }
        for (int i = 0; i < getCommentsCount(); i++) {
          if (!getComments(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object feedId_ = "";
      /**
       * <code>required string feed_id = 1;</code>
       */
      public boolean hasFeedId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string feed_id = 1;</code>
       */
      public java.lang.String getFeedId() {
        java.lang.Object ref = feedId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            feedId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string feed_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFeedIdBytes() {
        java.lang.Object ref = feedId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          feedId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string feed_id = 1;</code>
       */
      public Builder setFeedId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        feedId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string feed_id = 1;</code>
       */
      public Builder clearFeedId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        feedId_ = getDefaultInstance().getFeedId();
        onChanged();
        return this;
      }
      /**
       * <code>required string feed_id = 1;</code>
       */
      public Builder setFeedIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        feedId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.xiaomi.zhibo.crawler.pb.PbComment.Comment> comments_ =
        java.util.Collections.emptyList();
      private void ensureCommentsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          comments_ = new java.util.ArrayList<com.xiaomi.zhibo.crawler.pb.PbComment.Comment>(comments_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.xiaomi.zhibo.crawler.pb.PbComment.Comment, com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder, com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder> commentsBuilder_;

      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public java.util.List<com.xiaomi.zhibo.crawler.pb.PbComment.Comment> getCommentsList() {
        if (commentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(comments_);
        } else {
          return commentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public int getCommentsCount() {
        if (commentsBuilder_ == null) {
          return comments_.size();
        } else {
          return commentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public com.xiaomi.zhibo.crawler.pb.PbComment.Comment getComments(int index) {
        if (commentsBuilder_ == null) {
          return comments_.get(index);
        } else {
          return commentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public Builder setComments(
          int index, com.xiaomi.zhibo.crawler.pb.PbComment.Comment value) {
        if (commentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommentsIsMutable();
          comments_.set(index, value);
          onChanged();
        } else {
          commentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public Builder setComments(
          int index, com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder builderForValue) {
        if (commentsBuilder_ == null) {
          ensureCommentsIsMutable();
          comments_.set(index, builderForValue.build());
          onChanged();
        } else {
          commentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public Builder addComments(com.xiaomi.zhibo.crawler.pb.PbComment.Comment value) {
        if (commentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommentsIsMutable();
          comments_.add(value);
          onChanged();
        } else {
          commentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public Builder addComments(
          int index, com.xiaomi.zhibo.crawler.pb.PbComment.Comment value) {
        if (commentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommentsIsMutable();
          comments_.add(index, value);
          onChanged();
        } else {
          commentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public Builder addComments(
          com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder builderForValue) {
        if (commentsBuilder_ == null) {
          ensureCommentsIsMutable();
          comments_.add(builderForValue.build());
          onChanged();
        } else {
          commentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public Builder addComments(
          int index, com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder builderForValue) {
        if (commentsBuilder_ == null) {
          ensureCommentsIsMutable();
          comments_.add(index, builderForValue.build());
          onChanged();
        } else {
          commentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public Builder addAllComments(
          java.lang.Iterable<? extends com.xiaomi.zhibo.crawler.pb.PbComment.Comment> values) {
        if (commentsBuilder_ == null) {
          ensureCommentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, comments_);
          onChanged();
        } else {
          commentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public Builder clearComments() {
        if (commentsBuilder_ == null) {
          comments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          commentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public Builder removeComments(int index) {
        if (commentsBuilder_ == null) {
          ensureCommentsIsMutable();
          comments_.remove(index);
          onChanged();
        } else {
          commentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder getCommentsBuilder(
          int index) {
        return getCommentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder getCommentsOrBuilder(
          int index) {
        if (commentsBuilder_ == null) {
          return comments_.get(index);  } else {
          return commentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public java.util.List<? extends com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder> 
           getCommentsOrBuilderList() {
        if (commentsBuilder_ != null) {
          return commentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(comments_);
        }
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder addCommentsBuilder() {
        return getCommentsFieldBuilder().addBuilder(
            com.xiaomi.zhibo.crawler.pb.PbComment.Comment.getDefaultInstance());
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder addCommentsBuilder(
          int index) {
        return getCommentsFieldBuilder().addBuilder(
            index, com.xiaomi.zhibo.crawler.pb.PbComment.Comment.getDefaultInstance());
      }
      /**
       * <code>repeated .com.xiaomi.zhibo.crawler.pb.Comment comments = 2;</code>
       */
      public java.util.List<com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder> 
           getCommentsBuilderList() {
        return getCommentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xiaomi.zhibo.crawler.pb.PbComment.Comment, com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder, com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder> 
          getCommentsFieldBuilder() {
        if (commentsBuilder_ == null) {
          commentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.xiaomi.zhibo.crawler.pb.PbComment.Comment, com.xiaomi.zhibo.crawler.pb.PbComment.Comment.Builder, com.xiaomi.zhibo.crawler.pb.PbComment.CommentOrBuilder>(
                  comments_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          comments_ = null;
        }
        return commentsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsReq)
    }

    static {
      defaultInstance = new MultiCreateFeedCommentsReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsReq)
  }

  public interface MultiCreateFeedCommentsRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 err_code = 1;</code>
     */
    boolean hasErrCode();
    /**
     * <code>required uint32 err_code = 1;</code>
     */
    int getErrCode();

    /**
     * <code>optional string errMsg = 2;</code>
     */
    boolean hasErrMsg();
    /**
     * <code>optional string errMsg = 2;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string errMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsRsp}
   */
  public static final class MultiCreateFeedCommentsRsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsRsp)
      MultiCreateFeedCommentsRspOrBuilder {
    // Use MultiCreateFeedCommentsRsp.newBuilder() to construct.
    private MultiCreateFeedCommentsRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MultiCreateFeedCommentsRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MultiCreateFeedCommentsRsp defaultInstance;
    public static MultiCreateFeedCommentsRsp getDefaultInstance() {
      return defaultInstance;
    }

    public MultiCreateFeedCommentsRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MultiCreateFeedCommentsRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errCode_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errMsg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp.class, com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<MultiCreateFeedCommentsRsp> PARSER =
        new com.google.protobuf.AbstractParser<MultiCreateFeedCommentsRsp>() {
      public MultiCreateFeedCommentsRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiCreateFeedCommentsRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MultiCreateFeedCommentsRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ERR_CODE_FIELD_NUMBER = 1;
    private int errCode_;
    /**
     * <code>required uint32 err_code = 1;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 err_code = 1;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int ERRMSG_FIELD_NUMBER = 2;
    private java.lang.Object errMsg_;
    /**
     * <code>optional string errMsg = 2;</code>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string errMsg = 2;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      errCode_ = 0;
      errMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasErrCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, errCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, errCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsRsp)
        com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp.class, com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp.Builder.class);
      }

      // Construct using com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_descriptor;
      }

      public com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp getDefaultInstanceForType() {
        return com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp.getDefaultInstance();
      }

      public com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp build() {
        com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp buildPartial() {
        com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp result = new com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errMsg_ = errMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp) {
          return mergeFrom((com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp other) {
        if (other == com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp.getDefaultInstance()) return this;
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000002;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiaomi.zhibo.crawler.pb.PbComment.MultiCreateFeedCommentsRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int errCode_ ;
      /**
       * <code>required uint32 err_code = 1;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 err_code = 1;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>required uint32 err_code = 1;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000001;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 err_code = 1;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsRsp)
    }

    static {
      defaultInstance = new MultiCreateFeedCommentsRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.xiaomi.zhibo.crawler.pb.MultiCreateFeedCommentsRsp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_zhibo_crawler_pb_Comment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xiaomi_zhibo_crawler_pb_Comment_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PbComment.proto\022\033com.xiaomi.zhibo.craw" +
      "ler.pb\"\216\001\n\007Comment\022\020\n\010from_uid\030\001 \002(\004\022\017\n\007" +
      "content\030\002 \002(\t\022\023\n\013create_time\030\003 \002(\004\022\016\n\006to" +
      "_uid\030\004 \001(\004\022\025\n\rfrom_nickname\030\005 \001(\t\022\023\n\013to_" +
      "nickname\030\006 \001(\t\022\017\n\007is_good\030\007 \001(\010\"e\n\032Multi" +
      "CreateFeedCommentsReq\022\017\n\007feed_id\030\001 \002(\t\0226" +
      "\n\010comments\030\002 \003(\0132$.com.xiaomi.zhibo.craw" +
      "ler.pb.Comment\">\n\032MultiCreateFeedComment" +
      "sRsp\022\020\n\010err_code\030\001 \002(\r\022\016\n\006errMsg\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xiaomi_zhibo_crawler_pb_Comment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xiaomi_zhibo_crawler_pb_Comment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_xiaomi_zhibo_crawler_pb_Comment_descriptor,
        new java.lang.String[] { "FromUid", "Content", "CreateTime", "ToUid", "FromNickname", "ToNickname", "IsGood", });
    internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsReq_descriptor,
        new java.lang.String[] { "FeedId", "Comments", });
    internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_xiaomi_zhibo_crawler_pb_MultiCreateFeedCommentsRsp_descriptor,
        new java.lang.String[] { "ErrCode", "ErrMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
