// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbFeedsStatStore.proto

package com.xiaomi.zhibo.crawler.pb;

public final class PbFeedsStatStore {
  private PbFeedsStatStore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FeedsStatStoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xiaomi.zhibo.crawler.pb.FeedsStatStore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 commentCount = 1;</code>
     *
     * <pre>
     *评论数
     * </pre>
     */
    boolean hasCommentCount();
    /**
     * <code>optional int64 commentCount = 1;</code>
     *
     * <pre>
     *评论数
     * </pre>
     */
    long getCommentCount();

    /**
     * <code>optional int64 viewcount = 2;</code>
     *
     * <pre>
     *观看人数
     * </pre>
     */
    boolean hasViewcount();
    /**
     * <code>optional int64 viewcount = 2;</code>
     *
     * <pre>
     *观看人数
     * </pre>
     */
    long getViewcount();

    /**
     * <code>optional int64 likeCount = 3;</code>
     *
     * <pre>
     *赞计数
     * </pre>
     */
    boolean hasLikeCount();
    /**
     * <code>optional int64 likeCount = 3;</code>
     *
     * <pre>
     *赞计数
     * </pre>
     */
    long getLikeCount();
  }
  /**
   * Protobuf type {@code com.xiaomi.zhibo.crawler.pb.FeedsStatStore}
   */
  public static final class FeedsStatStore extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.xiaomi.zhibo.crawler.pb.FeedsStatStore)
      FeedsStatStoreOrBuilder {
    // Use FeedsStatStore.newBuilder() to construct.
    private FeedsStatStore(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FeedsStatStore(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FeedsStatStore defaultInstance;
    public static FeedsStatStore getDefaultInstance() {
      return defaultInstance;
    }

    public FeedsStatStore getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FeedsStatStore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              commentCount_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              viewcount_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              likeCount_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore.class, com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore.Builder.class);
    }

    public static com.google.protobuf.Parser<FeedsStatStore> PARSER =
        new com.google.protobuf.AbstractParser<FeedsStatStore>() {
      public FeedsStatStore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedsStatStore(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FeedsStatStore> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int COMMENTCOUNT_FIELD_NUMBER = 1;
    private long commentCount_;
    /**
     * <code>optional int64 commentCount = 1;</code>
     *
     * <pre>
     *评论数
     * </pre>
     */
    public boolean hasCommentCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 commentCount = 1;</code>
     *
     * <pre>
     *评论数
     * </pre>
     */
    public long getCommentCount() {
      return commentCount_;
    }

    public static final int VIEWCOUNT_FIELD_NUMBER = 2;
    private long viewcount_;
    /**
     * <code>optional int64 viewcount = 2;</code>
     *
     * <pre>
     *观看人数
     * </pre>
     */
    public boolean hasViewcount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 viewcount = 2;</code>
     *
     * <pre>
     *观看人数
     * </pre>
     */
    public long getViewcount() {
      return viewcount_;
    }

    public static final int LIKECOUNT_FIELD_NUMBER = 3;
    private long likeCount_;
    /**
     * <code>optional int64 likeCount = 3;</code>
     *
     * <pre>
     *赞计数
     * </pre>
     */
    public boolean hasLikeCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 likeCount = 3;</code>
     *
     * <pre>
     *赞计数
     * </pre>
     */
    public long getLikeCount() {
      return likeCount_;
    }

    private void initFields() {
      commentCount_ = 0L;
      viewcount_ = 0L;
      likeCount_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, commentCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, viewcount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, likeCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, commentCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, viewcount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, likeCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xiaomi.zhibo.crawler.pb.FeedsStatStore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xiaomi.zhibo.crawler.pb.FeedsStatStore)
        com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore.class, com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore.Builder.class);
      }

      // Construct using com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        commentCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        viewcount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        likeCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_descriptor;
      }

      public com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore getDefaultInstanceForType() {
        return com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore.getDefaultInstance();
      }

      public com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore build() {
        com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore buildPartial() {
        com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore result = new com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commentCount_ = commentCount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.viewcount_ = viewcount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.likeCount_ = likeCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore) {
          return mergeFrom((com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore other) {
        if (other == com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore.getDefaultInstance()) return this;
        if (other.hasCommentCount()) {
          setCommentCount(other.getCommentCount());
        }
        if (other.hasViewcount()) {
          setViewcount(other.getViewcount());
        }
        if (other.hasLikeCount()) {
          setLikeCount(other.getLikeCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiaomi.zhibo.crawler.pb.PbFeedsStatStore.FeedsStatStore) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long commentCount_ ;
      /**
       * <code>optional int64 commentCount = 1;</code>
       *
       * <pre>
       *评论数
       * </pre>
       */
      public boolean hasCommentCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 commentCount = 1;</code>
       *
       * <pre>
       *评论数
       * </pre>
       */
      public long getCommentCount() {
        return commentCount_;
      }
      /**
       * <code>optional int64 commentCount = 1;</code>
       *
       * <pre>
       *评论数
       * </pre>
       */
      public Builder setCommentCount(long value) {
        bitField0_ |= 0x00000001;
        commentCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 commentCount = 1;</code>
       *
       * <pre>
       *评论数
       * </pre>
       */
      public Builder clearCommentCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commentCount_ = 0L;
        onChanged();
        return this;
      }

      private long viewcount_ ;
      /**
       * <code>optional int64 viewcount = 2;</code>
       *
       * <pre>
       *观看人数
       * </pre>
       */
      public boolean hasViewcount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 viewcount = 2;</code>
       *
       * <pre>
       *观看人数
       * </pre>
       */
      public long getViewcount() {
        return viewcount_;
      }
      /**
       * <code>optional int64 viewcount = 2;</code>
       *
       * <pre>
       *观看人数
       * </pre>
       */
      public Builder setViewcount(long value) {
        bitField0_ |= 0x00000002;
        viewcount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 viewcount = 2;</code>
       *
       * <pre>
       *观看人数
       * </pre>
       */
      public Builder clearViewcount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        viewcount_ = 0L;
        onChanged();
        return this;
      }

      private long likeCount_ ;
      /**
       * <code>optional int64 likeCount = 3;</code>
       *
       * <pre>
       *赞计数
       * </pre>
       */
      public boolean hasLikeCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 likeCount = 3;</code>
       *
       * <pre>
       *赞计数
       * </pre>
       */
      public long getLikeCount() {
        return likeCount_;
      }
      /**
       * <code>optional int64 likeCount = 3;</code>
       *
       * <pre>
       *赞计数
       * </pre>
       */
      public Builder setLikeCount(long value) {
        bitField0_ |= 0x00000004;
        likeCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 likeCount = 3;</code>
       *
       * <pre>
       *赞计数
       * </pre>
       */
      public Builder clearLikeCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        likeCount_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.xiaomi.zhibo.crawler.pb.FeedsStatStore)
    }

    static {
      defaultInstance = new FeedsStatStore(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.xiaomi.zhibo.crawler.pb.FeedsStatStore)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026PbFeedsStatStore.proto\022\033com.xiaomi.zhi" +
      "bo.crawler.pb\"L\n\016FeedsStatStore\022\024\n\014comme" +
      "ntCount\030\001 \001(\003\022\021\n\tviewcount\030\002 \001(\003\022\021\n\tlike" +
      "Count\030\003 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_xiaomi_zhibo_crawler_pb_FeedsStatStore_descriptor,
        new java.lang.String[] { "CommentCount", "Viewcount", "LikeCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
